### ISSUE TITLE
Release notes should mention backwards incompatible changes

### ISSUE THREAD

**Issue by jsma** [divio/djangocms-link#101]
There was recently a migration to rename fields on the Link model, this should be documented in the release notes since anyone who interacted directly with `Link` objects likely has broken code now.

Also, the path for the default template was changed, so any template overrides will be ignored after updating to 2.0.*.

Finally, several variables were removed from the context when rendering the template so any template overrides that depended on the old context variables will break.

**Comment by czpython** [comment]
@FinalAngel Can you update the changelog for 2.0.0 accordingly?

**Comment by FinalAngel** [comment]
Yep will do
