### ISSUE TITLE
Make use of the PageSmartLinkField from django-cms

### ISSUE THREAD

**Issue by johnraz** [divio/djangocms-link#11]
I think we could merge both link and page field in one field in the same fashion we did it for the redirect field in django-cms.

Also this relates to divio/django-cms#2916, as you are using a FK here and we are not in the redirect field...  would be nice to have the same behavior in both.

If you agree, I will try to make this happen in django-cms so we can just inherit from that here.

edit: also it would drop the django-select2 dependency.

**Comment by FinalAngel** [comment]
There are new facilities now available. I'll be looking at this shortly and check our options.

**Comment by FinalAngel** [comment]
closing as the related cms issues has also been closed. @johnraz if you add the facilities in django-cms, I'll incorporate in here
