### ISSUE TITLE
django-select2 issues

### ISSUE THREAD

**Issue by jsma** [divio/djangocms-link#118]
I just enabled django-select2 per the README and I've encountered a few issues.

For example, I have a CMS page with a link to the home page that was created with the default select widgets, not django-select2. 

<img width="337" alt="screen shot 2017-01-26 at 2 25 09 am" src="https://cloud.githubusercontent.com/assets/24574/22328056/1e64b410-e36f-11e6-87ae-017cd1ec9247.png">

Next I set `DJANGOCMS_LINK_USE_SELECT2 = True` in my settings file. When I reload, the link plugin no longer shows the existing link to the home page, the auto-complete field is empty.

<img width="330" alt="screen shot 2017-01-26 at 2 25 32 am" src="https://cloud.githubusercontent.com/assets/24574/22328083/3c2d3e36-e36f-11e6-9e7c-dfe8355eec86.png">

If I then use the django-select2 widget to select the home page, I get the following error:

<img width="338" alt="screen shot 2017-01-26 at 2 25 46 am" src="https://cloud.githubusercontent.com/assets/24574/22328092/4a0e7b6e-e36f-11e6-92ea-3671ccea21d8.png">

Any ideas? Are there any additional steps required on my part beyond what is mentioned in the current README?

**Comment by FinalAngel** [comment]
@jsma thank you for the report, Is there any way you could open a PR with the fix? I'll most likely won't get to it till next week.

**Comment by FinalAngel** [comment]
@jsma sadly have no useful update here, I can reproduce and know the issue is somewhere in https://github.com/divio/djangocms-link/blob/master/djangocms_link/models.py#L148 I'll check with @czpython as I'd like to release it today.

**Comment by jsma** [comment]
Thanks for checking into this! I have not had time to troubleshoot further, so ended up disabling django-select2 for now.
