### ISSUE TITLE
Internal Link to Page on another Site

### ISSUE THREAD

**Issue by stefanfoulis** [divio/djangocms-link#121]
In a multisite setup an internal link may need to contain the domain to be valid. Currently this is not the case.

https://github.com/divio/djangocms-link/blob/2.1.1/djangocms_link/models.py#L134

It is unclear how to cleanly fix this. If we need to include the domain in the link it means we have to know stuff about the protocol (``http`` vs ``https``). In the example below I've chosen to use the protocol agnostic notation for the link. But this is not correct for all cases, as different sites may differing configurations regarding ``http`` and ``https``.

```
    def get_link(self):
        if self.internal_link_id:
            link = self.internal_link.get_absolute_url()
            if (
                not self.page or
                self.page and self.internal_link.site_id != self.page.site_id
            ):
                link = '//{}{}'.format(
                    self.internal_link.site.domain,
                    link,
                )
        elif ...
```

**Comment by stefanfoulis** [comment]
@FinalAngel it is not an edge case. This is a problem with all multisite projects. In the UI you can choose the other site (-> other domain) to pick the link to a cms page. But that information never gets used as part of the link.

**Comment by FinalAngel** [comment]
@stefanfoulis thank you, would you be able to propose a pull request?

**Comment by FinalAngel** [comment]
also needs to be incorporated in https://github.com/aldryn/aldryn-bootstrap3/issues/143
