### ISSUE TITLE
No selectable pages

### ISSUE THREAD

**Issue by marksweb** [divio/djangocms-link#122]
I've got a really strange problem with an EC2 server. There are no selectable pages in the drop down :(

Running locally, connected to the same db, I get selectable pages. Also on a virtual server for development I can get a choice of pages, the database here is based on the same database and running the same code as the EC2 server.

I've also got a custom plugin which provides internal page links, using the same form field code that this plugin uses which has the same issues.

Is the page query which populates the field cached? I've got cache clearing available via a link in admin, clearing cache doesn't help the issue, so I'm just confused.

**Comment by FinalAngel** [comment]
@marksweb I've never heard or seen such an issue, maybe @divio/django-cms-core has an idea? Otherwise we could help debug through the [Expert Help](https://www.divio.com/en/expert)

**Comment by stefanfoulis** [comment]
@marksweb I think the dropdown only shows published pages. So maybe none of
your pages have been published yet?

**Comment by marksweb** [comment]
Pages are all published. I've even been over everything & even switched the queryset to pull in drafts and public pages & it just won't load anything.

Really bizarre.

**Comment by czpython** [comment]
@marksweb can you try with the console open? Maybe there's something there.

**Comment by marksweb** [comment]
@czpython Now that seemed too simple, but looks like there's a problem!

<img width="1427" alt="screen shot 2017-03-27 at 23 41 53" src="https://cloud.githubusercontent.com/assets/1461191/24381280/68d26828-1347-11e7-875f-7e48ab61a3dd.png">

Looks like there's something funny going on with static paths.

The project is a duplicate of a Django 1.8.9 & CMS 3.1.7 project, then updated through to Django 1.10.x and CMS 3.4.2

I don't think there were any static changes I missed in upgrade notes because I've not seen issues with static files elsewhere.

**Comment by FinalAngel** [comment]
@marksweb the reason why the pages don't show up is that javascript initialisation fails. It seems very likely that there are some issues in the staticfile setup. It also says forbidden and not "not found". Very likely not an issue on djangocms-link itself.

**Comment by marksweb** [comment]
@FinalAngel Yeah the 403 is from S3 so effectively a 404, but I get that it's a static setup issue. It's just terribly annoying because the only difference between the server where it works, and where it doesn't is HTTPS where it doesn't, and a different sub bucket. Hopefully I'll figure it out soon!

**Comment by marksweb** [comment]
@FinalAngel How does `bundle.admin.widget.min.js` get added to the DOM? I can only see where the page select JS is declared in the widget class and can't see a problem with the `Media` classes declared at that point.

But there must be a comma missing somewhere in order for the two paths not to be separate. The below is what I get with `DEBUG = False`, but in debug mode they render as two separate S3 static paths;
![screen shot 2017-04-11 at 10 09 43](https://cloud.githubusercontent.com/assets/1461191/24902398/dc6bcbc0-1ea1-11e7-853c-6735570b951d.png)

I understand why you'd point at the staticfiles setup, but the difference in those settings between a server that works and a server that doesn't, is the sub-bucket.

**Comment by vxsx** [comment]
This looks like a bug in the django cms core.
The bundle is injected with webpack and to determine the url this is used https://github.com/divio/django-cms/blob/release/3.4.x/cms/static/cms/js/modules/get-dist-path.js#L2

Temporary workaround would be to disable hashing so the bundle names wouldn't be rewritten.
Also it would be great if you could reopen this on django-cms repo
