### ISSUE TITLE
Internal links to published pages

### ISSUE THREAD

**Issue by digiology** [divio/djangocms-link#131]
Hello,

I notice that the drop-down for internal links only shows draft pages. Why is that? Shouldn't it be possible to add a link to a page that has already been published?

Ross

**Comment by digiology** [comment]
Actually, the dropdown shows nothing for me even when I set `self.fields['internal_link'].queryset` in the form. But there is another dropbox id_internal_link_2 which is hidden (display:None) that contains all the pages.

**Comment by FinalAngel** [comment]
hello @digiology what browser are you using. It might be related to https://github.com/divio/django-cms/pull/6042

**Comment by czpython** [comment]
This is a design decision.
All apps using `PageField` will get draft only versions.
A page is always guaranteed to have a draft version but not always a public version, if we were to link to a public version then it would not be possible to properly prepare pages before publishing.
