### ISSUE TITLE
Found no way to edit link when display name was forgotten

### ISSUE THREAD

**Issue by fp4code** [divio/djangocms-link#137]
In a CKEditor Text Plugin, if a Link is created leaving blank the display name entry, there is no way to edit it. I see three solutions
- add documentation if there is a way to edit the link!
- add something like _missing display name_ if the field is blank
- authorize link editing in page structure

**Comment by FinalAngel** [comment]
With django CMS 3.4+ you can use the structure mode to edit the link. Alternatively you may want to adapt the template itself to show a (missing display name) text. I do not think this is necessary to document but I'm happy to review a PR :)
