### ISSUE TITLE
Display link with some custom style

### ISSUE THREAD

**Issue by 8ksoft** [divio/djangocms-link#14]
Could be useful to add some form field choice to add class="myclass" to the HTML included in the in the template. As a use case, suppose do you want to display a link as a Twitter Bootstrap Button, adding class="btn btn-default".

May be this choices, would be configurable via settings, in case you use another CSS framework, or custom css stylesheet. Or just disable this field in case you want the standard LinkPlugin.

Another simple solution for this is to create another ButtonLinkPlugin class, with the same model (or another inherited from LinkPlugin with extra cssclass field), the same form (or another inherited from LinkForm), and another template... I don know.. just some ideas.

**Comment by FinalAngel** [comment]
Will be adding this soon through djangocms-attributes-field :)

**Comment by FinalAngel** [comment]
added in https://github.com/divio/djangocms-link/pull/94
