### ISSUE TITLE
migration from "cmsplugin_filer_link"

### ISSUE THREAD

**Issue by jedie** [divio/djangocms-link#144]
djangocms-link is the successor of cmsplugin_filer_link

As requested in https://github.com/divio/django-cms/issues/6198#issuecomment-362598714 : Is there any guide on how to migration from "cmsplugin_filer_link" to "djangocms-link" ?

**Comment by FinalAngel** [comment]
Sadly not, but we welcome any PR to add a migration path or management script.

**Comment by FinalAngel** [comment]
Closing as we've deprecated cmsplugin-filer for a while now. Please re-open if someone is willing to propose a PR :)
