### ISSUE TITLE
Unable to override template

### ISSUE THREAD

**Issue by chitak** [divio/djangocms-link#147]
I have copied the folder to my template folder but I am unable to override the template.
I am trying to editing the link.html and select my template from djangocms, but it does not have any effect, it seems to me it always render the 'default' template.

> <MYPROJECT(This is the folder where settings.py reside)>/templates/djangocms_link/mybutton/link.html

settings.py

> DJANGOCMS_LINK_TEMPLATES = [
>     ('mybutton', 'My Button'),
> ]

I don't know what goes wrong, can anyone here help?

Thanks

**Comment by FinalAngel** [comment]
I just tested with a sample app and the settings you added:

``/templates/djangocms_link/mybutton/link.html``

It worked perfectly. You may need to look into your templates dirs settings configuration. Mine looked like this:

```
'DIRS': env('TEMPLATE_DIRS', [os.path.join(settings['BASE_DIR'], 'templates')], )
```
