### ISSUE TITLE
'NoneType' object has no attribute 'node'

### ISSUE THREAD

**Issue by joeljv91** [divio/djangocms-link#154]
Hi,

I updated djangocms-link from version 2.1.2 to 2.2.1 and I get this error when I enter to some page I get this error:

<img width="1427" alt="screenshot 2018-11-23 at 10 08 08" src="https://user-images.githubusercontent.com/7562185/48935358-c1cc4780-ef07-11e8-84e2-f4aabe80c317.png">

I need to migrate any data which affect to this update?

I'm using DjangoCMS 3.5.3 and this plugin djangocms-bootstrap4 1.2.0 which inherits from your djangocms-link.

Thanks

**Comment by joeljv91** [comment]
it does not matter I just saw the pull request:

https://github.com/divio/djangocms-link/pull/153

**Comment by FinalAngel** [comment]
@joeljv91 has the issue been resolved for you using 2.2.2?

**Comment by fsbraun** [comment]
**It does for me**, however, would it make sense to also replace ``ref_page.site_id`` by ``ref_page_site_id`` in [line 151](https://github.com/vThaian/djangocms-link/blob/5c8237c4e6edfb9d1b42a5120b78dbfdda46c762/djangocms_link/models.py#L151) of ``models.py``after going through the hassle of detecting the node to get the site id?

**Comment by FinalAngel** [comment]
@fsbraun I'll have a look :)
