### ISSUE TITLE
Translations/transifex

### ISSUE THREAD

**Issue by syntaxhr** [divio/djangocms-link#156]
Hello, I could easily translate the plugin for Croatian, Bosnian, Serbian and Italian languages but transifex says that you exceeded the subscription and the files are no more editable.
Let me know if I can help and how.

**Comment by FinalAngel** [comment]
@syntaxhr would you be able to create screenshot or a video capturing the issue you are experiencing so we could investigate or eventually call their support? On the account itself I see no restrictions.
