### ISSUE TITLE
Having no corresponding entrie in cms_page_placeholders results in AttributeError

### ISSUE THREAD

**Issue by mogoh** [divio/djangocms-link#161]
I am trying to migrate date from the old cmsplugin_filer_link to the newer djangocms-link. Now for some unknown reason some database entries have no page-placeholders-relation entries. I am not sure why and if this is a bug so maybe my database needs to be fixed, too. (Does this needs to be fixed?)

But those missing entries creats some `AttributeError: 'NoneType' object has no attribute 'node'` errors and I think I know why. This is the `djangocms_link.models.AbstractLink.get_link()`-function:

```python
    def get_link(self):
        if self.internal_link:
            ref_page = self.internal_link
            link = ref_page.get_absolute_url()

            # simulate the call to the unauthorized CMSPlugin.page property
            cms_page = self.placeholder.page if self.placeholder_id else None
            if getattr(cms_page, 'node'):
                ref_page_site_id = ref_page.node.site_id
                cms_page_site_id = getattr(cms_page.node, 'site_id', None)
            else:
                ref_page_site_id = ref_page.site_id
                cms_page_site_id = getattr(cms_page, 'site_id', None)

            if ref_page_site_id != cms_page_site_id:
                ref_site = Site.objects._get_site_by_id(ref_page.site_id).domain
                link = '//{}{}'.format(ref_site, link)
        elif self.external_link:
            link = self.external_link
        elif self.phone:
            link = 'tel:{}'.format(self.phone.replace(' ', ''))
        elif self.mailto:
            link = 'mailto:{}'.format(self.mailto)
        else:
            link = ''
        if (not self.phone and not self.mailto) and self.anchor:
            link += '#{}'.format(self.anchor)

        return link
```

If the corresponding page-placeholders-relation doesn't exist `self.placeholder.page` will be `None`, so `cms_page` will be `None` so `getattr(cms_page, 'node')` will raise the exception.

I suggest changing `if getattr(cms_page, 'node'):` to `if getattr(cms_page, 'node', None):` but I am not sure if this work for all cases.

**Comment by vThaian** [comment]
Hello, @mogoh. Do you using 2.2.0 version, right? Please upgrade your djangocms-link to the newest version `2.2.2`. Problem with `AttributeError: 'NoneType' object has no attribute 'node'` was resolved there.

**Comment by mogoh** [comment]
Yes, almost. I used 2.2.1. I updated and the problem went away. I can't believe, that I stumbled upon this bug right in the 10-day-time-window when it got fixed. Thanks. 😄
