### ISSUE TITLE
Link doesn't appear in the plugins list

### ISSUE THREAD

**Issue by masaruduy** [divio/djangocms-link#163]
![screen shot 2018-12-15 at 1 42 02 pm](https://user-images.githubusercontent.com/7341054/50046288-5ccfc180-006f-11e9-9f50-97f272a26352.png)

'djangocms_link', is Included INSTALLED_APPS

The 'normal' Link plugin doesn't appear on the plugins list even though the BS4 one shows up:
![screen shot 2018-12-15 at 1 45 14 pm](https://user-images.githubusercontent.com/7341054/50046320-b2a46980-006f-11e9-90e4-fc654e8fef4e.png)

**Comment by FinalAngel** [comment]
@masaruduy the Link plugin is removed by Bootstrap 4:
https://github.com/divio/djangocms-bootstrap4/blob/master/djangocms_bootstrap4/contrib/bootstrap4_link/cms_plugins.py#L83

**Comment by tacc-wbomar** [comment]
If one needs both `LinkPlugin` and `Bootstrap4LinkPlugin`, one may install as a single-file app to re-register the `LinkPlugin`.

<details>
<summary>Instructions</summary>

1. In `settings.py` to `INSTALLED_APPS` add `'YOUR_APP_DIR.PLUGIN_APP_DIR.bootstrap4_djangocms_link',`.
2. Add file `YOUR_APP_DIR/PLUGIN_APP_DIR/bootstrap4_djangocms_link.py`.
3. Populate `.../bootstrap4_djangocms_link.py` with code that:
    1. loads `LinkPlugin`
    2. restores `LinkPlugin`'s original fields (for the relevant version)
    3. registers `LinkPlugin`

Where `PLUGIN_APP_DIR` is a directory where you store plugin apps; Bootstrap4 and Django use `contrib`.

</details>

<details>
<summary>Minimal Code</summary>

```python
from cms.plugin_pool import plugin_pool
from djangocms_link.cms_plugins import LinkPlugin

LinkPlugin.fieldsets[0][1]['fields'] = (
    'name',
    ('external_link', 'internal_link'),
)

plugin_pool.register_plugin(LinkPlugin)
```

</details>

<details>
<summary>Complete Code for My Use Case</summary>

```python
# Reregister unregistered LinkPlugin without uninstalling Bootstrap4LinkPlugin
# FAQ: A Bootstrap link is undesirable but may be used by migrated legacy sites
# TODO: Let migrated legacy sites load non-standard suite of legacy plugins
# FAQ: If we can import both plugins, then re-register LinkPlugin
#      (because Bootstrap4Link unregistered LinkPlugin)
try:
    from cms.plugin_pool import plugin_pool
    from djangocms_link.cms_plugins import LinkPlugin
    from djangocms_bootstrap4.contrib.bootstrap4_link.cms_plugins import Bootstrap4LinkPlugin

    # Restore original fields
    # SEE: https://github.com/django-cms/djangocms-bootstrap4/blob/2.0.0/djangocms_bootstrap4/contrib/bootstrap4_link/cms_plugins.py#L26-L42
    # SEE: https://github.com/django-cms/djangocms-link/blob/3.0.0/djangocms_link/cms_plugins.py#L20-L23
    LinkPlugin.fieldsets[0][1]['fields'] = (
        'name',
        ('external_link', 'internal_link'),
    )

    # SEE: https://github.com/django-cms/djangocms-link/issues/163
    plugin_pool.register_plugin(LinkPlugin)
# CAVEAT: If plugins exist but import statement is inaccurate… silent failure
except ImportError:
    pass
```

</details>
