### ISSUE TITLE
LinkPlugin is silently unregistered by bootstrap4_link

### ISSUE THREAD

**Issue by FabriceSalvaire** [divio/djangocms-link#167]
I am trying to upgrade to Django CMS v3.6.

Despite I have `djangocms_link` in **INSTALLED_APPS**, `cms check` reports

` - LinkPlugin has instances but is no longer installed [ERROR]`

**Comment by vThaian** [comment]
Could you please @FabriceSalvaire paste more details? From which version are you trying to migrate? Which Django version are you using? Could you paste your traceback?
150/5000

**Comment by FabriceSalvaire** [comment]
After investigation (put print statements in cms code) I discovered that `djangocms_bootstrap4.contrib.bootstrap4_link` unregister `djangocms_link.cms_plugins.LinkPlugin` which breaks my cms

**Comment by FinalAngel** [comment]
@FabriceSalvaire it is intended behaviour to unregister djangocms-link when using djangocms-bootstrap4. Alternatively you can use bootstrap4 but without the link implementation?

**Comment by tacc-wbomar** [comment]
For others who have this problem, there is a similar complaint and a solution: https://github.com/django-cms/djangocms-link/issues/163#issuecomment-868818891
