### ISSUE TITLE
Misunderstanding between README and CHANGELOG

### ISSUE THREAD

**Issue by DmytroLitvinov** [divio/djangocms-link#169]
Hi there,

According to [CHANGELOG](https://github.com/divio/djangocms-link/blob/master/CHANGELOG.rst#240-2019-04-16) in version 2.4.0 support for Django<2 was dropped, but it still is used in [tests(CI)](https://github.com/divio/djangocms-link/blob/master/tox.ini#L2), it is written as [classifiers for PyPi](https://github.com/divio/djangocms-link/blob/master/setup.py#L29).

If you need help with removing mention of django<2, please ping me and I will prepare PR.

**Comment by FinalAngel** [comment]
@DmytroLitvinov we only removed support for Django 2.0 as it is not officially supported anymore. 1.11 is still supported :)
