### ISSUE TITLE
djangocms-link requirements

### ISSUE THREAD

**Issue by botanicvelious** [divio/djangocms-link#176]
djangocms-link requires at least django-filer==1.5.0 however the dependency tree doesnt specify that in any package.

```
django-filer==1.4.2
  - aldryn-newsblog==2.2.1 [requires: django-filer>=1.4.2]
  - aldryn-people==2.2.0 [requires: django-filer]
    - aldryn-newsblog==2.2.1 [requires: aldryn-people>=2.2.0]
  - djangocms-audio==1.1.0 [requires: django-filer>=1.2.4]
  - djangocms-file==2.3.0 [requires: django-filer>=1.2.4]
  - djangocms-googlemap==1.3.0 [requires: django-filer>=1.3.0]
  - djangocms-link==2.5.0 [requires: django-filer>=1.3.0]
  - djangocms-picture==2.3.0 [requires: django-filer>=1.3.0]
  - djangocms-video==2.1.1 [requires: django-filer>=1.2.4]
```

**Comment by FinalAngel** [comment]
@botanicvelious thanks for the report, I'll have a look as soon as I can :)

**Comment by FinalAngel** [comment]
@botanicvelious I've tested it locally and django filer 1.3 is not necessarily required. If you run Django 2.0/2.1 you require django-filer 1.4 and for Django 2.2 you need filer 1.5. For Django 1.11 (which is still supported) >=1.3 is okay to use.

**Comment by rvanlaar** [comment]
I'm curious as to how you tested it.

I've just tested it. djangocms-link migration 0014 depends on django-filer migration 0011.
This migration is only in django-filer >= 1.5.0

**Comment by rvanlaar** [comment]
The error:

> django.db.migrations.exceptions.NodeNotFoundError: Migration djangocms_link.0014_link_file_link dependencies reference nonexistent parent node ('filer', '0011_auto_20190418_0137')
