### ISSUE TITLE
Please Upgrade Django Filer requirements to 1.5.0.

### ISSUE THREAD

**Issue by rvanlaar** [divio/djangocms-link#177]
A new issue since #176 was closed and hasn't been reopened:

djangocms-link migration 0014 depends on django-filer migration 0011.
This migration is only in django-filer >= 1.5.0

    django.db.migrations.exceptions.NodeNotFoundError: Migration djangocms_link.0014_link_file_link dependencies reference nonexistent parent node ('filer', '0011_auto_20190418_0137')

**Comment by FinalAngel** [comment]
done, release pending :)

**Comment by k-funk** [comment]
Also have this issue. Hoping a new release will solve it for me.
