### ISSUE TITLE
Select2 Django 2.2.7

### ISSUE THREAD

**Issue by mateoreyes** [divio/djangocms-link#180]
Hi,

I am using DjangoCMS 3.7, Django 2.1.7 and djangocms-link 2.3.1. Configure django select 2 and it works fine.
But if I change the version of Django to 2.2.7 django select 2 does not work.

I see the following message in the browser console: TypeError: $ element.select2 is not a function (django_select2.js: 48: 14)

**Comment by jrief** [comment]
which version of django-select2 are you using?

**Comment by mateoreyes** [comment]
django-select2  7.2.0

**Comment by FinalAngel** [comment]
As a reference: https://github.com/applegrew/django-select2/issues/586
