### ISSUE TITLE
Class option

### ISSUE THREAD

**Issue by donce** [divio/djangocms-link#23]
What do you think about adding class option to the model? We use several different link classes, so option like this is crucial for us - maybe it's worth adding it for everybody? I can make a pull request if you agree.

**Comment by greenstatic** [comment]
+1

**Comment by mkoistinen** [comment]
I typically avoid this by enclosing it in a Style tag. (aldryn-style, or djangocms-style). Won't this solve it for you?

**Comment by greenstatic** [comment]
@mkoistinen as dirty solution i just wrapped the placeholder in a <span> tag and added my class there. But i suppose your method would work as well :)
