### ISSUE TITLE
djangocms-ckeditor + djangocms-link

### ISSUE THREAD

**Issue by leesolway** [divio/djangocms-link#32]
An ongoing issue with multiple versions, the link plugin does not render within the ckeditor, when editing an existing plugin. No markup representing the link is being rendered into the editor. The issue only seems to exist when editing an existing plugin, it renders fine when adding a new one. 

Current versions:
Django==1.6.8
djangocms-text-ckeditor==2.4.1
djangocms-link==1.5
django-cms==3.0.7

Steps:
Add a djangocms-ckeditor plugin
Add an djangocms-link plugin inline
Click source or save and re-edit

**Comment by strindhaug** [comment]
The above suggestion didn't work for me. But I got it to work somehow..
I'm using Django==1.7.1 and djangocms-text-ckeditor==2.4.2, and a "fork" of djangocms-link (e.g. manually copied and modified to add link to a custom article type)

Adding:
TEXT_ADDITIONAL_TAGS = ('img')
to settings.py

and removing icon_src() and get_form() from the my cms plugin worked. It actually displays like a link and not using an ugly icon. Not sure why or how it works, but it does. Maybe it uses the template from render_template to display in visual mode.

**Comment by thnee** [comment]
Removing `icon_src` and `icon_alt` from my (extension of) the `LinkPlugin` solved the issue for me. Not sure exactly what the intentions were in the design here, but this seems like an acceptable solution for now.
