### ISSUE TITLE
page_link field hidden by default when using Select2

### ISSUE THREAD

**Issue by marksweb** [divio/djangocms-link#39]
Is there something that you need to do to get the select2 version of `page_link` to display?

If I import the standard CMS page select field it is visible in the form, but if I use Select2 there's a class of 'hidden' added to the field.

I really like the select2 field, so have I missed something glaringly obvious in the settings to get it to display?

**Comment by yakky** [comment]
See https://github.com/divio/djangocms-link#installation: you need to enable and configure django-select2

**Comment by marksweb** [comment]
I installed it, added it to installed apps, added the URL include and it still didn't show itself. If you removed the hidden class from it, it is there, as a Select2 field working as expected.

But I wasn't going to write specific JS to remove the hidden class.

**Comment by yakky** [comment]
@marksweb can't reproduce that. which django-select2 version are you using?

**Comment by marksweb** [comment]
@yakky Annoying, I don't think there's anything special that would effect anything. I've got version 4.2.2 installed, but I can see thats a bit old now.
