### ISSUE TITLE
 'render_plugin' fails

### ISSUE THREAD

**Issue by Kurdym** [divio/djangocms-link#5]
As soon as I try to insert a link, I get this error:

In template E:\.virtualenvs\vcms235\lib\site-packages\djangocms_link\templates\cms\plugins\link.html, error at line 1
Invalid block tag: 'render_plugin', expected 'empty' of 'endfor'
1 	{% load cms_tags %}{% if object.child_plugin_instances %}<span class="plugin_link">{% endif %}<a href="{{ link }}"{% if target %} target="{{ target }}"{% endif %}>{% for plugin in object.child_plugin_instances %}{% render_plugin plugin %}{% empty %}{{ name }}{% endfor %}</a>{% if object.child_plugin_instances %}</span>{% endif %}

When I comment out "{% render_plugin plugin %}", it runs further

**Comment by FinalAngel** [comment]
Please update to at least Django 1.6+. New version will be Django < 1.8 compatible
