### ISSUE TITLE
Unwanted migration with django 1.7

### ISSUE THREAD

**Issue by saeedsq** [divio/djangocms-link#54]
Python 2.7.8
Django 1.7.8
Django CMS 3.1.0
djangocms-link 1.6.2

Running makemigrations creates unwanted migration for djangocms_link:

class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_link', '0003_auto_20150212_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='anchor',
            field=models.CharField(help_text='This applies only to page and text links. Do <em>not</em> include a preceding "#" symbol.', max_length=128, verbose_name='anchor', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='link', validators=[djangocms_link.validators.IntranetURLValidator(intranet_host_re=None)]),
            preserve_default=True,
        ),
    ]

**Comment by jsma** [comment]
There is a pull request to fix this #57. The migration is necessary, just need it included in the next version of djangocms-link so it doesn't trigger the migrations auto detector in our own projects.

**Comment by yakky** [comment]
Fixed by #57
