### ISSUE TITLE
_get_media in forms.py pulling in select2 css files intermittently

### ISSUE THREAD

**Issue by chriswedgwood** [divio/djangocms-link#55]
When I start my server and open I use django-cms link with select2 the page field displays correctly.
When I save and then re-open the page field is displayed weirdly because the CSS files arent being loaded by _get_media

Anyone else getting this behaviour?

pip freeze:
https://gist.github.com/chriswedgwood/ff0d2d66fb413d66fbfe

console output:
https://gist.github.com/chriswedgwood/0b7521a8f2829e7e104c

Before
![before](https://cloud.githubusercontent.com/assets/1273523/8261859/c0889dec-16c5-11e5-88b7-82ec07beec07.png)

After
![after](https://cloud.githubusercontent.com/assets/1273523/8261860/c08902dc-16c5-11e5-9a0e-69eda8938213.png)

**Comment by imikael21** [comment]
Yes, I get the same behaviour, with the same versions of Django, Django-CMS and djangocms-link.

**Comment by yakky** [comment]
@imikael21 which version of Django-select2 is installed?

**Comment by imikael21** [comment]
@yakky Django-Select2==4.3.1

**Comment by yakky** [comment]
@imikael21 does 4.2.2 behaves any different?

**Comment by imikael21** [comment]
@yakky strangely with django-select2 4.2.2, the page field does not appear at all...
Another hint : switching back to version 4.3.1, the page field shows correctly the first time I try to edit a link in a text plugin

![image](https://cloud.githubusercontent.com/assets/6333379/8393860/0fe26f82-1d22-11e5-8455-84cc99391c45.png)

But once the editing window has been closed, I get the same weird display each time I try to edit a link.

**Comment by yakky** [comment]
I suspect some issue with django-select2, then

**Comment by chriswedgwood** [comment]
I installed latest version of Select2 and it works now so next release will see this behaviour disappear

**Comment by yakky** [comment]
Fixed in django-select2
