### ISSUE TITLE
pip install djangocms-link fails on Ubuntu 14.04 with python 3.4.0 and Django 1.8

### ISSUE THREAD

**Issue by lswest** [divio/djangocms-link#56]
I'm setting up a Django-CMS instance on a Digital Ocean Ubuntu 14.04 VPS.  I've installed Python 3.4.0, Django 1.8 and used a requirements.txt file to install the packages from my testing area.  However, of the list, only djangocms-link fails to build and install.  The error is as follows:

    Collecting djangocms-link
    Downloading djangocms-link-1.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-2nuoeqle/djangocms-link/setup.py", line 36, in <module>
        long_description=open('README.rst').read(),
      File "/usr/share/nginx/python/code-root/env/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1844: ordinal not in range(128)
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2nuoeqle/djangocms-link

Based off the error, I have a feeling the README.rst file is in unicode encoding, but for some reason Python thinks it's ascii.  But I'm by no means certain of this.

I have successfully installed the package in the last two days on both Ubuntu 15.04 and Mac OS X, which means it could just as easily be an issue on my server.  However, I'm not sure then what to make of the error, nor am I sure how to test anything with a pip package like this.  Any advice/direction would be appreciated.

**Comment by ChristianKleineidam** [comment]
I can reproduce the error on Ubuntu 14.04 VPS with Python 3.4.0 and Django 1.8:

    pip install djangocms-link
    Collecting djangocms-link
      Using cached djangocms-link-1.6.2.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-pxwr25_g/djangocms-link/setup.py", line 36, in <module>
            long_description=open('README.rst').read(),
          File "/root/konnekt/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
            return codecs.ascii_decode(input, self.errors)[0]
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1844: ordinal not in range(128)

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pxwr25_g/djangocms-link

**Comment by lswest** [comment]
I just tried this again on the original server (after having done any pending updates).  Now version 1.6.2 installed without issue (using Ubuntu 14.04, Django 1.8.2, and Python 3.4.0).  See if you have any pending updates with ``sudo apt-get update && sudo apt-get upgrade``.

**Comment by ChristianKleineidam** [comment]
Unfortunately running `sudo apt-get update && sudo apt-get upgrade` doesn't help in my case.

**Comment by lswest** [comment]
Have you tried checking for updates to pip's installed packages?  You can update them all using ``pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U``(taken from [here](http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip))

If that doesn't help, then I'm out of ideas.  I'll leave the issue open, in the hopes that someone might know more.

**Comment by ChristianKleineidam** [comment]
Thanks, but it doesn't help.

**Comment by vmonteco** [comment]
I have the same problem but when I try to build a docker image from archlinux.

**Comment by vmonteco** [comment]
I finally managed to fix it :
I made a fork and just added something the *setup.py* file to be sure to make it read the file by using utf-8, just as someone suggested me on IRC :

        long_description=open("README.rst", 'r', encoding="utf-8").read(),

https://github.com/vmonteco/djangocms-link/blob/master/setup.py

Is it possible to submit this change?
You can try to use the fork I made in the meantime.

**Comment by louis-haddrell** [comment]
Still having this issue. Pull request fixes it.

Any chance of this getting merged sometime soon?

**Comment by fygul** [comment]
On my Windows 8.1, Python 3.4

>(env) D:\djangoCMS>pip install djangocms-link
>Collecting djangocms-link
>  Using cached djangocms-link-1.6.2.tar.gz
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
>      File "<string>", line 20, in <module>
>      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-_n62uy7g\djangocms-link\setup.py", line 36, in <module>
>        long_description=open('README.rst').read(),
>    UnicodeDecodeError: 'cp950' codec can't decode byte 0xc2 in position 1844: illegal multibyte sequence
>
>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-_n62uy7g\djangocms-link


There is a unicode space {U+00A0} at line 50 of README.rst:

>    #{U+00A0}RFC1123 Pattern:

**Comment by yakky** [comment]
Fixed by #64 
Thanks to all that contributed to solve this
