### ISSUE TITLE
Issue or browser/OS behaviour when editing a link?

### ISSUE THREAD

**Issue by marksweb** [divio/djangocms-link#59]
I've just had an issue raised with regard to editing an existing link in the editor.

If you double click on a link & the link dialog opens with only a part/word of the link selected, when you hit OK and save the link, it replaces the selected part of the link only. I'm not sure if that's easy to understand, so let me explain; if you have a link called `click here` and double click to edit it in the editor and the link dialog opens with only `here` selected, once you hit OK to save, the editor will then display `click click here`.

Is that initial selection behaviour controlled by the browser/OS or should the CKeditor/CMS ensure the whole link is selected when making the edit?

**Comment by jsma** [comment]
There is a similar issue reported for [cmsplugin-filer link plugin](https://github.com/stefanfoulis/cmsplugin-filer/issues/179). I've experienced this as well, have not had a chance to debug. Might need to rethink requiring a double click on the linked text as the UI...works fine for initial creation but attempts to edit are a pain for exactly the reasons you mention. Perhaps something similar to what GMail/Google Docs does where a pop-up appears that allows to change/remove the link.

<img width="460" alt="screen shot 2015-07-23 at 6 10 29 pm" src="https://cloud.githubusercontent.com/assets/24574/8865604/32a56508-3166-11e5-9c7f-9ad124a0778e.png">

**Comment by FinalAngel** [comment]
We did some fixes recently to ckeditor @jsma and @marksweb. was the problem resolved for you?

**Comment by marksweb** [comment]
Thanks @FinalAngel. Unfortunately I've been moved off CMS projects for a while, but I'll try to find time to look at that. I bet we won't be able to update at the moment though as most sites are running old versions of CMS 3.1.x

**Comment by jsma** [comment]
The recent updates do seem to solve these issue.
