### ISSUE TITLE
Phone field restrictions

### ISSUE THREAD

**Issue by nick-ernie** [divio/djangocms-link#63]
Hello.

Right now plugin have no restriction to the phone field, i think it will be great if phone links content will limited by digits and "+"/"-" chars and whitespaces .

Thanks.

**Comment by yakky** [comment]
@nick-ernie phone numbers format greatly varies across countries and as such can be quite complicated to come up with a comprehensive validation

**Comment by FinalAngel** [comment]
@yakky though we could add trimming to the CharField to remove at least the spaces? I could also add some very simple validation so only digits and +/-/() are allowed?
