### ISSUE TITLE
Add support for django-select2 5.0+

### ISSUE THREAD

**Issue by yakky** [divio/djangocms-link#78]
django-select2 5.0+ is a complete rewrite. This plugin is currently not compatible with it, but we need to make it compatible as it will be needed to support future Django versions

**Comment by FinalAngel** [comment]
Will do :)

**Comment by FinalAngel** [comment]
actually would need help for that integration, on hold until someone can help out.

**Comment by FinalAngel** [comment]
@yakky would you be able to add this?

**Comment by gkmngrgn** [comment]
hello everybody! @yakky did you make anything about this issue? Can you review my pull request? What do you think?
