### ISSUE TITLE
usage of select2 field should be configurable

### ISSUE THREAD

**Issue by stefanfoulis** [divio/djangocms-link#8]
currently the select2 field is automatically used for the page selector if select2 is installed. Otherwise it falls back to using the standard cms page selector widget.

The select2 widget is not really usable if you don't know exactly what page you want to add.
It should use the cms page selector widget by default and have a setting to enable select2 for the edge cases where there are so many pages that the select2 widget makes more sense.

**Comment by FinalAngel** [comment]
👍 will try to figure it out and make it optional through a setting

**Comment by FinalAngel** [comment]
now available: https://github.com/divio/djangocms-link/pull/94
