### ISSUE TITLE
'name' should be optional

### ISSUE THREAD

**Issue by macolo** [divio/djangocms-link#83]
Currently it seems to be impossible to wrap this link element around another plugin (i.e. image) without having to specify an anchor text for the link plugin.

This behaviour makes it difficult to use it together with other plugins. I suggest making the 'name' field optional.

**Comment by FinalAngel** [comment]
Sorry for the late reply, but we'll be having a look at this shortly!

**Comment by FinalAngel** [comment]
done in https://github.com/divio/djangocms-link/pull/94
