### ISSUE TITLE
Adding a style field to the link plugin?

### ISSUE THREAD

**Issue by furiousdave** [divio/djangocms-link#84]
An option I frequently use on sites where we have cmsplugin-filer installed is the ability to define a list of classes for use in a dropdown in the link plugin form. On sites where we use djangocms-link, I often find myself wishing the same feature was available. Would be a pretty simple addition if you think it makes sense to port over. https://github.com/divio/cmsplugin-filer/blob/develop/cmsplugin_filer_link/models.py#L29

Wondering what the devs here think. Thanks a lot.

**Comment by FinalAngel** [comment]
Sorry for the late reply, but we'll be having a look at this shortly!

**Comment by FinalAngel** [comment]
added in https://github.com/divio/djangocms-link/pull/94
