### ISSUE TITLE
Integrity errors due to missing data migration

### ISSUE THREAD

**Issue by stefanfoulis** [divio/djangocms-link#97]
https://github.com/divio/djangocms-link/blob/master/djangocms_link/migrations/0010_adapted_fields.py
removes the ``null=True`` on some fields, but it does not change any existing fields with ``NULL`` in them to an empty string.

This can cause ``django.db.utils.IntegrityError: column "mailto" contains null values``.

**Comment by stefanfoulis** [comment]
same problem for the other fields where ``null=True`` was removed.

**Comment by czpython** [comment]
Fixed by 19d13cbcae2dfadc4bcdccd8b454b36ac2366e24
